SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH AS MAX_LENGTH,
    IS_NULLABLE AS NULLABLE,
    COLUMN_DEFAULT AS DEFAULT_VALUE
FROM 
    INFORMATION_SCHEMA.COLUMNS
WHERE 
    TABLE_NAME = 'Books' AND 
    TABLE_SCHEMA = 'alx_book_store';